spring.application.name=beta
spring.datasource.url=jdbc:postgresql://localhost:5432/db_scopel
spring.datasource.username=postgres
spring.datasource.password=ljdwyscopel
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.enabled=true
spring.main.web-application-type=none