CREATE TABLE users (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    login VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(80) NOT NULL,
    role VARCHAR(9) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE
);